version: '3.8'

services:
  azuresqledge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: resellio_azuresqledge
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Rese11io
      MSSQL_PID: Developer                  
      MSSQL_DATABASE: resellioDB
    volumes:
      - azuresqledge_data:/var/opt/mssql
    ports:
      - 1433:1433
  
  redis:
    image: redis:latest
    container_name: resellio_redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
      
volumes:
  redis_data:
    driver: local
  azuresqledge_data:
    driver: local