version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: resellio_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: resellioDB
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  redis:
    image: redis:latest
    container_name: resellio_cart
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
      
volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local